<?php

declare(strict_types=1);

// Only our own code is checked - files generated by Symfony Flex recipes (config/bundles.php, public/index.php, bin/console) are left as is
$finder = (new PhpCsFixer\Finder())
    ->in([
        __DIR__.'/src',
        __DIR__.'/tests',
        __DIR__.'/migrations',
    ]);

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@PHP82Migration' => true,
        // Risky, but safe for this codebase: the whole project is written with strict types
        'declare_strict_types' => true,
        'strict_comparison' => true,
        'strict_param' => true,
        // Keep "use DateTimeImmutable;" imports instead of "\DateTimeImmutable" (the @Symfony default)
        'global_namespace_import' => [
            'import_classes' => true,
            'import_constants' => false,
            'import_functions' => false,
        ],
    ])
    ->setFinder($finder)
    ->setCacheFile(__DIR__.'/var/.php-cs-fixer.cache');
